baseURL = 'https://shinonome-shizuka.github.io'
copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。'
languageCode = "zh-Hans"
defaultContentLanguage = 'zh'
theme = 'dream'
title = '闲人后院'
# disqusShortname = 'shinonome-shizuka-github-io'

[params]
utterancesRepo = "shinonome-shizuka/shinonome-shizuka.github.io"
i18n = 'zh'
author = '東雲閑'
avatar = '/me/shizuka_new_bbg.png'
description = '闲人后院，闲人语。'
hasCJKLanguage = true
headerTitle = '闲人后院门不闭'
motto = '横剑听风雨浸溪，无上清凉花满席。</br><span style="font-size:12px;color: gray;">微信公众号 @shizuka_backyard</span>'

background = "#E3E3E3"
# backgroundImage = "/me/background.jpg"
linkColor = "#005CFF"

rss = true

# dark mode
defaultDark = true
backgroundDark = "#14191E"
backgroundImageDark = "/me/shinonome_background@2x.png"
darkLinkColor = "#005CFF"
darkNav = true
dark404 = true

email = "ps4@null.net"
# twitter = "g1eny0ung"
# facebook = "g1eny0ung"
instagram = "whitemage.null"
# mastodon = ""
# linkedin = "钺杨g1eny0ung"
# github = "g1eny0ung"
# stackoverflow = "5676489/g1eny0ung"
# codepen = "g1eny0ung"

siteStartYear = 2020

favicon = "/me/favicon.ico"

highlightjs = true
# highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
highlightjsExtraLanguages = ["ocaml"]
highlightjsTheme = "gruvbox-light"
highlightjsThemeDark = "gruvbox-dark"

# search
enableSearch = true

# options
showSummaryCoverInPost = true
# hasTwitterEmbed = true
# reversePostAndAside = true
shareInAside = true
# fixedNav = true
collapsibleTags = true
# collapseBySummary = true

[params.advanced]
customCSS = ["css/custom.css"]
# customJSBefore = []
# customJS = []

[params.experimental]
jsDate = true
jsDateFormat = "yyyy年MM月dd日"
