# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

description = "A hugo theme named dream"
features = [
  "flip",
  "masonry layout",
  "i18n",
  "blog",
  "google-analytics",
  "disqus",
  "responsive",
  "copyright",
  "avatar",
  "motto",
  "social links",
  "creative",
  "personal",
  "light mode",
  "dark mode",
  "search",
]
homepage = "https://g1eny0ung.site/hugo-theme-dream"
license = "MIT"
licenselink = "https://github.com/g1eny0ung/hugo-theme-dream/blob/master/LICENSE"
min_version = "0.57.2"
name = "Dream"
tags = [
  "flip",
  "masonry layout",
  "i18n",
  "blog",
  "google-analytics",
  "disqus",
  "responsive",
  "copyright",
  "avatar",
  "motto",
  "social links",
  "creative",
  "personal",
  "light mode",
  "dark mode",
  "search",
]

[author]
homepage = "https://github.com/g1eny0ung"
name = "Yue Yang"

# If porting an existing theme
[original]
homepage = "https://g1eny0ung.github.io"
name = "g1eny0ung's blog"
repo = "https://github.com/g1eny0ung/blog"
